---
- name: Repo_checker
  hosts:  Veeam_Linux_Repository
  become: yes
  become_user: veeam_repo

  tasks:
    - name: ensure iscsiadm tools are installed
      dnf:
        name: iscsiadmd
        state: latest

    - name: ensure iscsiadmd is started
      systemd:
        name: iscsiadmd
        state: started

    - name: ensure multipathd is at the latest version
      dnf:
        name: multipathd-server
        state: latest

    - name: ensure multipathd is started
      systemd:
        name: multipathd
        state: started
