- name: install updates
  hosts: all
  become: yes
  yum: name=* state=latest
  when: ansible_os_family == "RedHat
  
  #-name: Call Roles
   #hosts: Veeam_Linux_Repository
   #roles: 
    #-hostname
    #-firewalld
    #-ntp-config
    #-motd
