- name: Install updates
  hosts: Veeam_Linux_Repository
  become: yes
  tasks: 
 - name: update the system
    yum:
      name: "*"
      state: latest
  #when: ansible_os_family == "RedHat
  
  #-name: Call Roles
   #hosts: Veeam_Linux_Repository
   #roles: 
    #-hostname
    #-firewalld
    #-ntp-config
    #-motd
